//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrada
    {
        public int EntradaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public int PersonaId { get; set; }
        public string Destino { get; set; }
        public string Motivo { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
